export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_CART_PRODUCT: "ADD_CART_PRODUCT",
    CART_PRODUCTS: "CART_PRODUCTS",
  };